converge deb/rpm

diff --git a/omnibus/package-scripts/agent-rpm/posttrans b/omnibus/package-scripts/agent-rpm/posttrans
--- a/omnibus/package-scripts/agent-rpm/posttrans
+++ b/omnibus/package-scripts/agent-rpm/posttrans
@@ -7,10 +7,9 @@
 # .rpm: STEP 6 of 6
 
 INSTALL_DIR=/opt/datadog-agent
-CONFIG_DIR=/etc/datadog-agent
-SERVICE_NAME=datadog-agent
 LOG_DIR=/var/log/datadog
 CONFIG_DIR=/etc/datadog-agent
+SERVICE_NAME=datadog-agent
 
 # Create a symlink to the agent's binary
 ln -sf $INSTALL_DIR/bin/agent/agent /usr/bin/datadog-agent
@@ -61,18 +60,12 @@ if [ -f "$INSTALL_DIR/embedded/bin/python" ]; then
     ${INSTALL_DIR}/embedded/bin/python "${INSTALL_DIR}/python-scripts/post.py" "${INSTALL_DIR}" || true
 fi
 
+if [ -x ${INSTALL_DIR}/embedded/bin/fipsinstall.sh ]; then
+    ${INSTALL_DIR}/embedded/bin/fipsinstall.sh
+fi
+
 KNOWN_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon|Arista|SUSE|Rocky|AlmaLinux|Oracle)"
 DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_DISTRIBUTION || grep -Eo $KNOWN_DISTRIBUTION /etc/issue 2>/dev/null || grep -Eo $KNOWN_DISTRIBUTION /etc/Eos-release 2>/dev/null || grep -m1 -Eo $KNOWN_DISTRIBUTION /etc/os-release 2>/dev/null || uname -s)
-
-echo "Enabling service $SERVICE_NAME"
-if command -v systemctl >/dev/null 2>&1; then
-    systemctl enable $SERVICE_NAME || echo "[ WARNING ]\tCannot enable $SERVICE_NAME with systemctl"
-elif command -v initctl >/dev/null 2>&1; then
-    # start/stop policy is already defined in the upstart job file
-    :
-else
-    echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
-fi
 
 # Only install selinux policy on a few known distributions
 INSTALL_SELINUX_POLICY="false"
@@ -105,6 +98,7 @@ if [ "$INSTALL_SELINUX_POLICY" = "true" ]; then
                     echo "Couldn’t install system-probe policy."
                     echo "To be able to run system-probe on your host, please install or update the selinux-policy-targeted and"
                     echo "policycoreutils-python (or policycoreutils-python-utils depending on your distribution) packages."
+
                     echo "Then run the following commands, or reinstall datadog-agent:"
                     echo "    semodule -i $CONFIG_DIR/selinux/system_probe_policy.pp"
                     echo "    semanage fcontext -a -t system_probe_t $INSTALL_DIR/embedded/bin/system-probe"
@@ -158,10 +152,6 @@ install_method:
     echo "$install_info_content" >$CONFIG_DIR/install_info
 fi
 
-if [ -x ${INSTALL_DIR}/embedded/bin/fipsinstall.sh ]; then
-    ${INSTALL_DIR}/embedded/bin/fipsinstall.sh
-fi
-
 set +e
 generate_install_id() {
     # Try generating a UUID based on /proc/sys/kernel/random/uuid
@@ -190,7 +180,17 @@ if [ ! -f "$CONFIG_DIR/install.json" ]; then
     echo "$install_signature" >$CONFIG_DIR/install.json
     chown -R dd-agent:dd-agent ${CONFIG_DIR}
 fi
-set -e
+uset -e
+
+echo "Enabling service $SERVICE_NAME"
+if command -v systemctl >/dev/null 2>&1; then
+    systemctl enable $SERVICE_NAME || echo "[ WARNING ]\tCannot enable $SERVICE_NAME with systemctl"
+elif command -v initctl >/dev/null 2>&1; then
+    # start/stop policy is already defined in the upstart job file
+    :
+else
+    echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
+fi
 
 # TODO: Use a configcheck command on the agent to determine if it's safe to restart,
 # and avoid restarting when a check conf is invalid
